EVPLUS/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('home.urls')),
    path('auth/', include('usuario.urls')),
    path('eventos/', include('eventos.urls')),
    path('conta/', include('conta.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eventos/urls.py
#urls.py

from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

app_name = 'eventos'

urlpatterns = [
    path('', views.eventos, name='eventos'),
    path('meuseventos/', views.listarEventos, name='meuseventos'),
    path('minhasinscricoes/', views.listarEventosInscritos, name='minhasinscricoes'),
    path('detalhes/<int:id>/', views.detalhesEvento, name='detalhes_evento'),
    path('editar/<int:id>/', views.editarEvento, name='editar_evento'),
    path('cancelar/<int:id>/', views.cancelarEvento, name='cancelar_evento'),
    path('todos-eventos/', views.listarTodosEventos, name='todos_eventos'),
    path('inscricao/<int:evento_id>/', views.inscricaoEvento, name='inscricao_evento'),
    path('cancelar-inscricao/<int:evento_id>/', views.cancelarInscricao, name='cancelar_inscricao'),
    path('finalizar/<int:id>/', views.finalizarEvento, name='finalizar_evento'),
    path('apagar/<int:id>/', views.apagarEvento, name='apagar_evento'),
    path('enviar-certificado/<int:evento_id>/', views.enviarCertificado, name='enviar_certificado'),
    path('download-certificado/<int:evento_id>/', views.downloadCertificado, name='download_certificado'),
    path('avaliar-evento/<int:evento_id>/', views.enviarAvaliacao, name='enviar_avaliacao'),
    path('deletar-avaliacao/<int:avaliacao_id>/', views.deletarAvaliacao, name='deletar_avaliacao'),
    path('erro/', views.erro, name='erro'),
]

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),

]

home/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'home.html')

home/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block 'head' %}
    <link rel="stylesheet" href="{% static 'home/css/home.css' %}">
{% endblock %}

{% block 'title' %}Descubra eventos!{% endblock %}

{% block 'dashboard' %}
    <div class="banner-principal">
        <label for="title-home-1">Eventos em destaque</label>
        <div class="banner-container-g" id="banner-img" onmousedown="startDrag(event)">
            <div class="banner">
                <div class="banner-image">
                    <img src="{% get_media_prefix %}banners/exemplo5.jpg" alt="Banner 1" style="transform: scale(1.3);">
                    <a href="{% url 'eventos:detalhes_evento' 54 %}">
                        <label for="name">Reunião Universitaria</label>
                        <label for="name" style="margin-left: 170px">11/11</label>
                        <label for="name" style="margin-left: 222px">19:00h</label>
                    </a>
                </div>
            </div>            
            <div class="banner">
                <div class="banner-image">
                    <img src="{% get_media_prefix %}banners/exemplo6.jpg" alt="Banner 2" style="transform: scale(1.3);">
                <label for="name">Campeonato de Jogos</label>
                </div>
            </div>
            <div class="banner">
                <div class="banner-image">
                    <img src="{% get_media_prefix %}banners/exemplo8.jpg" alt="Banner 3" style="transform: scale(1.3);">
                <label for="name">Interclasse</label>
                </div>
            </div>
            <div class="banner">
                <div class="banner-image">
                    <img src="{% get_media_prefix %}banners/exemplo9.jpg" alt="Banner 3" style="transform: scale(1.3);">
                <label for="name">Roda de Capoeira</label>
                </div>
            </div>
            <div class="banner">
                <div class="banner-image">
                    <img src="{% get_media_prefix %}banners/exemplo10.jpg" alt="Banner 3" style="transform: scale(1.3);">
                <label for="name">Discussão sobre BITCOIN (Online)</label>
                </div>
            </div>
        </div>
    </div>

    <div class="banner-p">
        <label for="title-home-2">Eventos por Categoria</label>
        <div class="banner-container-p" id="banner-cat" onmousedown="startDragP(event)">
            <div class="banner-cat">
                <div class="banner-cat1">
                <img src="{% static 'images/placeholder1.jpg' %}" alt="Categoria 1">
                <a href="{% url 'eventos:todos_eventos' %}?categoria=Tecnologia">
                <label for="name">Tecnologia</label>
                </a>
                </div>
            </div>
            <div class="banner-cat">
                <div class="banner-cat2">
                    <img src="{% static 'images/placeholder2.jpg' %}" alt="Categoria 2">
                    <a href="{% url 'eventos:todos_eventos' %}?categoria=Saúde">
                    <label for="name">Saúde</label>
                    </a>
                    </div>
            </div>
            <div class="banner-cat">
                <div class="banner-cat3">
                    <img src="{% static 'images/placeholder3.jpg' %}" alt="Categoria 3">
                    <a href="{% url 'eventos:todos_eventos' %}?categoria=Educação">
                    <label for="name">Educação</label>
                    </a>
                </div>
            </div>
            <div class="banner-cat">
                <div class="banner-cat4">
                    <img src="{% static 'images/placeholder4.jpg' %}" alt="Categoria 4">
                    <a href="{% url 'eventos:todos_eventos' %}?categoria=Esporte">
                    <label for="name">Esportes</label>
                    </a>
                </div>
            </div>
            <div class="banner-cat">
                <div class="banner-cat5">
                    <img src="{% static 'images/placeholder5.jpg' %}" alt="Categoria 5">
                    <a href="{% url 'eventos:todos_eventos' %}?categoria=Cultura">
                    <label for="name">Cultura</label>
                    </a>
                </div>
            </div>
            <div class="banner-cat">
                <div class="banner-cat6">
                    <img src="{% static 'images/placeholder6.jpg' %}" alt="Categoria 6">
                    <a href="{% url 'eventos:todos_eventos' %}?categoria=Gastronomia">
                    <label for="name">Gastronomia</label>
                    </a>
                </div>
            </div>
            <div class="banner-cat">
                <div class="banner-cat7">
                    <img src="{% static 'images/placeholder7.jpg' %}" alt="Categoria 7">
                    <a href="{% url 'eventos:todos_eventos' %}?categoria=Negócios">
                    <label for="name">Negócios</label>
                    </a>
                </div>
            </div>
            <div class="banner-cat">
                <div class="banner-cat8">
                    <img src="{% static 'images/placeholder8.jpg' %}" alt="Categoria 8">
                    <a href="{% url 'eventos:todos_eventos' %}?categoria=Comemoração">
                    <label for="name">Comemoração</label>
                    </a>
                </div>
            </div>
            <div class="banner-cat">
                <div class="banner-cat9">
                    <img src="{% static 'images/placeholder9.jpg' %}" alt="Categoria 9">
                    <a href="{% url 'eventos:todos_eventos' %}?categoria=Artes">
                    <label for="name">Arte</label>
                    </a>
                </div>
            </div>
            <div class="banner-cat">
                <div class="banner-cat10">
                    <img src="{% static 'images/placeholder10.jpg' %}" alt="Categoria 10">
                    <a href="{% url 'eventos:todos_eventos' %}?categoria=Outros">
                    <label for="name">Outros</label>
                    </a>
                </div>
            </div>
        </div>
    </div>

    <div class="banner-p">
        <label for="title-home-3">Eventos relacionados ao seu gosto</label>
        <div class="banner-container-p" id="banner-cat" onmousedown="startDragP(event)">       
            <div class="banner-cat">
                <div class="banner-cat10">
                    <img src="{% static 'images/placeholder10.jpg' %}" alt="Categoria 10">
                    <a href="{% url 'eventos:todos_eventos' %}?categoria=Outros">
                    <label for="name">Outros</label>
                    </a>
                </div>
            </div>
        </div>
    </div>

    <div class="banner-s">
        <label for="title-home-4">Eventos nos próximos dias</label>
        <div class="banner-container-s" id="banner-s" onmousedown="startDragS(event)">
            <div class="banner-storie">
                <div class="banner-s1">
                    <a href="{% url 'home' %}">
                    <img src="{% static 'images/placeholder11.jpg' %}" alt="Categoria 1">
                    <label for="name">Vaqueijada - 31/04</label>
                    </a>
                </div>
            </div>
            <div class="banner-storie">
                <div class="banner-s2">
                    <a href="{% url 'home' %}">
                    <img src="{% static 'images/placeholder14.jpg' %}" alt="Categoria 2">
                    <label for="name">Evento de Nerd - 11/05</label>
                    </a>
                </div>
            </div>
        </div>
    </div>

    <script src="{% static 'home/js/home.js' %}"></script>
{% endblock %}