EVPLUS/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('home.urls')),
    path('auth/', include('usuario.urls')),
    path('eventos/', include('eventos.urls')),
    path('conta/', include('conta.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eventos/urls.py
#urls.py

from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

app_name = 'eventos'

urlpatterns = [
    path('', views.eventos, name='eventos'),
    path('meuseventos/', views.listarEventos, name='meuseventos'),
    path('minhasinscricoes/', views.listarEventosInscritos, name='minhasinscricoes'),
    path('detalhes/<int:id>/', views.detalhesEvento, name='detalhes_evento'),
    path('editar/<int:id>/', views.editarEvento, name='editar_evento'),
    path('cancelar/<int:id>/', views.cancelarEvento, name='cancelar_evento'),
    path('todos-eventos/', views.listarTodosEventos, name='todos_eventos'),
    path('inscricao/<int:evento_id>/', views.inscricaoEvento, name='inscricao_evento'),
    path('cancelar-inscricao/<int:evento_id>/', views.cancelarInscricao, name='cancelar_inscricao'),
    path('finalizar/<int:id>/', views.finalizarEvento, name='finalizar_evento'),
    path('apagar/<int:id>/', views.apagarEvento, name='apagar_evento'),
    path('enviar-certificado/<int:evento_id>/', views.enviarCertificado, name='enviar_certificado'),
    path('download-certificado/<int:evento_id>/', views.downloadCertificado, name='download_certificado'),
    path('avaliar-evento/<int:evento_id>/', views.enviarAvaliacao, name='enviar_avaliacao'),
    path('deletar-avaliacao/<int:avaliacao_id>/', views.deletarAvaliacao, name='deletar_avaliacao'),
    path('erro/', views.erro, name='erro'),
]

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),

]

eventos/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator

class Evento(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    clients = models.ManyToManyField(User, through='Inscricao', related_name='eventos')
    name = models.CharField(max_length=100)
    description = models.TextField()
    local = models.CharField(max_length=100)
    date = models.DateField()
    time = models.TimeField()
    category = models.CharField(max_length=100)
    banner = models.ImageField(null=True, blank=True, upload_to='banners/')
    limite_inscricoes = models.PositiveIntegerField(null=True, blank=True, verbose_name="Limite de Inscrições")
    finalizado = models.BooleanField(default=False)
    certificados = models.ManyToManyField(User, through='Certificado', related_name='eventos_certificados')
    avaliacoes = models.ManyToManyField(User, through='Avaliacao', related_name='eventos_avaliados')

    def __str__(self):
        return self.name
    
class Inscricao(models.Model):
    evento = models.ForeignKey(Evento, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        unique_together = ['evento', 'user']

class Certificado(models.Model):
    evento = models.ForeignKey(Evento, on_delete=models.CASCADE)
    participante = models.ForeignKey(User, on_delete=models.CASCADE)
    arquivo = models.FileField(upload_to='certificados/')

    def __str__(self):
        return f"Certificado de {self.participante.username} para {self.evento.name}"

class Avaliacao(models.Model):
    evento = models.ForeignKey(Evento, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    nota = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    comentario = models.TextField()

    class Meta:
        unique_together = ['evento', 'user']

templates/base.html
{% load static %}
<!doctype html>
<html lang="pt-BR">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
  <link rel="stylesheet" href="{% static 'general/css/base.css' %}">
  <link rel="stylesheet" href="{% static 'general/css/general.css' %}">
  <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
  <link rel="icon" href="{% static 'images/LOGO_16x16.png' %}" type="image/png">

  {% block 'head' %}{% endblock %}

  <title>{% block 'title' %}{% endblock %}</title>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark p-3">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'home' %}" style="margin-left: 205px;">
        <img src="{% static 'images/LOGO.png' %}" alt="Logo" class="logo">
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
  
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link mx-2" href="{% url 'eventos:todos_eventos' %}">Todos os Eventos</a>
          </li>
          {% if user.is_authenticated %}
          {% if perms.eventos.add_evento %}
          <li class="nav-item">
            <a class="nav-link mx-2" href="{% url 'eventos:eventos' %}">Criar Evento</a>
          </li>
          {% endif %}
          {% endif %}
        </ul>
        <ul class="navbar-nav ml-auto" style="margin-right: 205px;">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class='bx bx-user'></i>
              {% if user.is_authenticated %}
                {{ user.username }}
              {% else %}
                <span class="logged-out-indicator">Entre na sua conta!</span>
              {% endif %}
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'conta' %}">Minha Conta</a>
                {% if user.is_authenticated %}
                {% if perms.eventos.view_evento %}
                  <a class="dropdown-item" href="{% url 'eventos:minhasinscricoes' %}">Minhas Inscrições</a>
                {% endif %}
                {% if perms.eventos.add_evento %}
                  <a class="dropdown-item" href="{% url 'eventos:meuseventos' %}">Meus Eventos</a>
                {% endif %}
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'logout' %}">Sair</a>
              {% endif %}
            </div>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <div id="sidebar-container">
    <div class="sidebar">
      <a href="{% url 'eventos:todos_eventos' %}" class="custom-link">Todos os Eventos</a>
      <a href="{% url 'conta' %}" class="custom-link">Minha Conta</a>
    {% if user.is_authenticated %}
    {% if perms.eventos.view_evento %}
      <a href="{% url 'eventos:minhasinscricoes' %}" class="custom-link">Minhas Inscrições</a>
    {% endif %}
    {% if perms.eventos.add_evento %}
      <a href="{% url 'eventos:meuseventos' %}" class="custom-link">Meus Eventos</a>
    {% endif %}
      <a href="{% url 'logout' %}" class="custom-link">Sair</a>
    {% endif %}
    </div>
  </div>

  <section class="home-section">
    <div class="page-topo" id="page-topo">
      <h1 class="main-title" id="page-topo-title"></h1>
    </div>
    {% block 'dashboard' %}
    {% endblock %}
  </section>

  {% block 'body' %}
  {% endblock %}
  
  <footer class="footer">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <p style="margin-right: 50px;">&copy; 2024 EVPLUS. Todos os direitos reservados.</p>
            </div>
        </div>
    </div>
  </footer>

  <script src="{% static 'general/js/base.js' %}"></script>
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
  <script>
    var pageTitle = document.title;
    var bannerTitle = document.getElementById("page-topo-title");
    bannerTitle.textContent = pageTitle;

    $(document).ready(function(){
      $('.dropdown-toggle').dropdown();

      $('.navbar-toggler').click(function(){
        $('#sidebar-container').toggleClass('show-sidebar');
      });
    });
  </script>
</body>
</html>