EVPLUS/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('home.urls')),
    path('auth/', include('usuario.urls')),
    path('eventos/', include('eventos.urls')),
    path('conta/', include('conta.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eventos/urls.py
#urls.py

from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

app_name = 'eventos'

urlpatterns = [
    path('', views.eventos, name='eventos'),
    path('meuseventos/', views.listarEventos, name='meuseventos'),
    path('minhasinscricoes/', views.listarEventosInscritos, name='minhasinscricoes'),
    path('detalhes/<int:id>/', views.detalhesEvento, name='detalhes_evento'),
    path('editar/<int:id>/', views.editarEvento, name='editar_evento'),
    path('cancelar/<int:id>/', views.cancelarEvento, name='cancelar_evento'),
    path('todos-eventos/', views.listarTodosEventos, name='todos_eventos'),
    path('inscricao/<int:evento_id>/', views.inscricaoEvento, name='inscricao_evento'),
    path('cancelar-inscricao/<int:evento_id>/', views.cancelarInscricao, name='cancelar_inscricao'),
    path('finalizar/<int:id>/', views.finalizarEvento, name='finalizar_evento'),
    path('apagar/<int:id>/', views.apagarEvento, name='apagar_evento'),
    path('enviar-certificado/<int:evento_id>/', views.enviarCertificado, name='enviar_certificado'),
    path('download-certificado/<int:evento_id>/', views.downloadCertificado, name='download_certificado'),
    path('avaliar-evento/<int:evento_id>/', views.enviarAvaliacao, name='enviar_avaliacao'),
    path('deletar-avaliacao/<int:avaliacao_id>/', views.deletarAvaliacao, name='deletar_avaliacao'),
    path('erro/', views.erro, name='erro'),
]

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),

]

eventos/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator

class Evento(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    clients = models.ManyToManyField(User, through='Inscricao', related_name='eventos')
    name = models.CharField(max_length=100)
    description = models.TextField()
    local = models.CharField(max_length=100)
    date = models.DateField()
    time = models.TimeField()
    category = models.CharField(max_length=100)
    banner = models.ImageField(null=True, blank=True, upload_to='banners/')
    limite_inscricoes = models.PositiveIntegerField(null=True, blank=True, verbose_name="Limite de Inscrições")
    finalizado = models.BooleanField(default=False)
    certificados = models.ManyToManyField(User, through='Certificado', related_name='eventos_certificados')
    avaliacoes = models.ManyToManyField(User, through='Avaliacao', related_name='eventos_avaliados')

    def __str__(self):
        return self.name
    
class Inscricao(models.Model):
    evento = models.ForeignKey(Evento, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        unique_together = ['evento', 'user']

class Certificado(models.Model):
    evento = models.ForeignKey(Evento, on_delete=models.CASCADE)
    participante = models.ForeignKey(User, on_delete=models.CASCADE)
    arquivo = models.FileField(upload_to='certificados/')

    def __str__(self):
        return f"Certificado de {self.participante.username} para {self.evento.name}"

class Avaliacao(models.Model):
    evento = models.ForeignKey(Evento, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    nota = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    comentario = models.TextField()

    class Meta:
        unique_together = ['evento', 'user']

eventos/forms.py
#forms.py

from django import forms
from .models import Evento
from .models import Certificado
from .models import Avaliacao

class EventoForm(forms.ModelForm):
    class Meta:
        model = Evento
        fields = ['name', 'description', 'local', 'date', 'time', 'category', 'banner', 'limite_inscricoes']
        exclude = ['user', 'clients', 'finalizado']

class CertificadoForm(forms.ModelForm):
    class Meta:
        model = Certificado
        fields = ['arquivo']
        
class AvaliacaoForm(forms.ModelForm):
    class Meta:
        model = Avaliacao
        fields = ['nota', 'comentario']

eventos/views.py
#views.py

from django.db.models import Avg
from .models import Evento, Certificado, Avaliacao
from .forms import EventoForm, CertificadoForm, AvaliacaoForm
from django.http import HttpResponse, FileResponse, JsonResponse
from django.contrib.auth.models import User
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required, permission_required
from django.utils import timezone

def erro(request):
    exibir_sidebar = True
    return render(request, 'erro.html', {'exibir_sidebar': exibir_sidebar})

@permission_required('eventos.add_evento', login_url='/auth/login/')
def eventos(request):

    if request.method == 'GET':
        eventos = Evento.objects.filter(user=request.user)
        return render(request, 'criarEvento.html', {'eventos': eventos})
    elif request.method == 'POST':
        form = EventoForm(request.POST, request.FILES)
        if form.is_valid():
            evento = form.save(commit=False)
            evento.user = request.user
            evento.save()
            return redirect('eventos:meuseventos')
        else:
            return render(request, 'criarEvento.html', {'form': form})

def finalizarEventosVencidos():
    eventos_vencidos = Evento.objects.filter(finalizado=False, date__lt=timezone.now())
    for evento in eventos_vencidos:
        evento.finalizado = True
        evento.save()
        
@login_required
@permission_required('eventos.add_evento', raise_exception=True)
def listarEventos(request):
    finalizarEventosVencidos()
    eventos_ativos = Evento.objects.filter(user=request.user, finalizado=False)
    eventos_finalizados = Evento.objects.filter(user=request.user, finalizado=True)
    
    for evento in eventos_ativos:
        if len(evento.name) > 15:
            evento.name = evento.name[:15] + '...'        
    for evento in eventos_finalizados:
        if len(evento.name) > 15:
            evento.name = evento.name[:15] + '...'
    
    return render(request, 'meusEventos.html', {'eventos': eventos_ativos, 'finalizarEvento': eventos_finalizados})

@permission_required('eventos.change_evento', login_url='/auth/login/')
def editarEvento(request, id):
    try:
        evento = Evento.objects.get(id=id, user=request.user)
    except Evento.DoesNotExist:
        evento = None
    
    if evento:
        if request.method == 'GET':
            form = EventoForm(instance=evento)
            return render(request, 'editarEvento.html', {'form': form, 'evento': evento})
        elif request.method == 'POST':
            form = EventoForm(request.POST, request.FILES, instance=evento)
            if form.is_valid():
                form.save()
                return redirect('eventos:meuseventos')
            else:
                return render(request, 'editarEvento.html', {'form': form, 'evento': evento})
    else:
        return render(request, 'erro.html')

def detalhesEvento(request, id):
    evento = get_object_or_404(Evento, id=id)
    comentarios = Avaliacao.objects.filter(evento=evento)
    media_notas = comentarios.aggregate(media=Avg('nota'))['media']
    
    if request.user.is_authenticated:
        avaliacao_usuario = Avaliacao.objects.filter(evento=evento, user=request.user).first()
    else:
        avaliacao_usuario = None
    
    permitir_avaliacao = True if not avaliacao_usuario else False
    
    return render(request, 'visualizarEvento.html', {'evento': evento, 'comentarios': comentarios, 'media_notas': media_notas})

def listarTodosEventos(request):
    finalizarEventosVencidos()
    categoria = request.GET.get('categoria')
    nome = request.GET.get('nome')
    
    eventosDisponiveis = Evento.objects.filter(finalizado=False) 
    
    if categoria:
        eventosDisponiveis = eventosDisponiveis.filter(category=categoria)
    if nome:
        eventosDisponiveis = eventosDisponiveis.filter(name__icontains=nome)
    
    for evento in eventosDisponiveis:
        if len(evento.name) > 15:
            evento.name = evento.name[:15] + '...'
        if len(evento.description) > 50:
            evento.description = evento.description[:50] + '...'
    
    return render(request, 'todosEventos.html', {'eventos': eventosDisponiveis})

@permission_required('eventos.delete_evento', login_url='/auth/login/')
def cancelarEvento(request, id):
    evento = Evento.objects.get(id=id)
    evento.delete()
    return redirect('eventos:meuseventos')

@permission_required('eventos.add_evento', login_url='/auth/login/')
def finalizarEvento(request, id):
    evento = Evento.objects.get(id=id)
    evento.finalizado = True
    evento.save()
    return redirect('eventos:meuseventos')

@login_required
def listarEventosInscritos(request):
    finalizarEventosVencidos()
    eventos = Evento.objects.filter(clients=request.user, finalizado=False)
    finalizarEvento = Evento.objects.filter(clients=request.user, finalizado=True)
    
    eventos_e_certificados = {}
    for evento in finalizarEvento:
        certificados = Certificado.objects.filter(evento=evento, participante=request.user)
        eventos_e_certificados[evento] = certificados
        
    for evento in eventos:
        if len(evento.name) > 15:
            evento.name = evento.name[:15] + '...' 
    for evento in finalizarEvento:
        if len(evento.name) > 15:
            evento.name = evento.name[:15] + '...' 
    
    return render(request, 'minhasInscricoes.html', {'eventos': eventos, 'finalizarEvento': finalizarEvento, 'eventos_e_certificados': eventos_e_certificados})

@permission_required('eventos.view_evento', login_url='/auth/login/')
def inscricaoEvento(request, evento_id):
    evento = get_object_or_404(Evento, pk=evento_id)
    if request.user not in evento.clients.all():
        evento.clients.add(request.user)
        evento.save()
        return redirect('eventos:minhasinscricoes')
    else:
        return redirect('eventos:detalhes_evento', id=evento_id)

@permission_required('eventos.view_evento', login_url='/auth/login/')   
def cancelarInscricao(request, evento_id):
    evento = get_object_or_404(Evento, pk=evento_id)
    if request.user in evento.clients.all():
        evento.clients.remove(request.user)
    return redirect('eventos:minhasinscricoes')

@permission_required('eventos.delete_evento', login_url='/auth/login/')
def apagarEvento(request, id):
    evento = Evento.objects.get(id=id)
    evento.delete()
    return redirect('eventos:meuseventos')

@login_required
@permission_required('eventos.add_evento', raise_exception=True)
def enviarCertificado(request, evento_id):
    evento = get_object_or_404(Evento, pk=evento_id)

    if request.method == 'POST':
        form = CertificadoForm(request.POST, request.FILES)
        if form.is_valid():
            arquivo = form.cleaned_data['arquivo']
            if request.POST.get('enviar_para_todos'):
                for participante in evento.clients.all():
                    certificado, created = Certificado.objects.get_or_create(evento=evento, participante=participante)
                    certificado.arquivo = arquivo
                    certificado.save()
            else:
                participante_id = request.POST.get('participante_selecionado')
                try:
                    participante = User.objects.get(pk=participante_id)
                    if participante in evento.clients.all():
                        certificado, created = Certificado.objects.get_or_create(evento=evento, participante=participante)
                        certificado.arquivo = arquivo
                        certificado.save()
                    else:
                        motivo_erro = "O participante selecionado não está inscrito no evento"
                        return render(request, 'erro.html', {'motivo_erro': motivo_erro})
                except User.DoesNotExist:
                    motivo_erro = "O participante selecionado não existe"
                    return render(request, 'erro.html',  {'motivo_erro': motivo_erro})

            return redirect('eventos:meuseventos')
    else:
        form = CertificadoForm()

    return render(request, 'enviarCertificado.html', {'form': form, 'evento': evento})

@login_required
@permission_required('eventos.view_evento', raise_exception=True)
def downloadCertificado(request, evento_id):
    evento = get_object_or_404(Evento, pk=evento_id)

    if request.user in evento.clients.all():
        certificados = Certificado.objects.filter(evento=evento, participante=request.user)
        
        if certificados.exists():
            certificado = certificados.first()
            return FileResponse(open(certificado.arquivo.path, 'rb'))
        else:
            motivo_erro = "O certificado não pertence ao usuário"
            return render(request, 'erro.html', {'motivo_erro': motivo_erro})
    else:
        motivo_erro = "O usuário não está inscrito no evento"
        return render(request, 'erro.html', {'motivo_erro': motivo_erro})

@login_required
@permission_required('eventos.view_evento', raise_exception=True)
def enviarAvaliacao(request, evento_id):
    evento = get_object_or_404(Evento, pk=evento_id)
    avaliacao_existente = Avaliacao.objects.filter(evento=evento, user=request.user).first()
    
    if request.method == 'POST':
        form = AvaliacaoForm(request.POST, instance=avaliacao_existente)
        if form.is_valid():
            avaliacao = form.save(commit=False)
            avaliacao.evento = evento
            avaliacao.user = request.user
            avaliacao.save()
            comentarios = evento.avaliacoes.all()
            return redirect('eventos:detalhes_evento', id=avaliacao.evento.id)
    else:
        form = AvaliacaoForm(instance=avaliacao_existente)
    
    comentarios = evento.avaliacoes.all() if evento.avaliacoes.exists() else []
    
    return redirect('eventos:detalhes_evento', id=avaliacao.evento.id)

@login_required
@permission_required('eventos.view_evento', login_url='/auth/login/')

eventos/templates/erro.html
{% extends 'base.html' %}
{% load static %}

{% block 'head' %}
    <link rel="stylesheet" href="{% static 'eventos/css/erro.css' %}">
{% endblock %}

{% block 'title' %}Erro{% endblock %}

{% block 'dashboard' %}
    <img src="{% static 'images/erro.jpg' %}" alt="erro" class="img-fluid">
    {% if motivo_erro %}
        <p>{{ motivo_erro }}</p>
    {% endif %}
    <script src="{% static 'eventos/js/meuseventos.js' %}"></script>
{% endblock %}

eventos/templates/minhasInscricoes.html
{% extends 'base.html' %}
{% load static %}

{% block 'head' %}
    <link rel="stylesheet" href="{% static 'eventos/css/meuseventos.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        .evento-card {
            display: inline-block;
            width: 263px;
            margin: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
            overflow: hidden;
        }
        .evento-thumbnail {
            width: 100%;
            height: 100px;
            background-size: cover;
            background-position: center;
        }
        .evento-info {
            padding: 10px;
        }
        .col-md-4 {
            margin-right: -90px;
            margin-left: -10px;
        }
    </style>
{% endblock %}

{% block 'title' %}Minhas Inscrições{% endblock %}

{% block 'dashboard' %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h5>Eventos Ativos</h5>
                <div class="row">
                    {% for evento in eventos %}
                        <div class="col-md-4">
                            <div class="evento-card">
                                {% if evento.banner %}
                                    <div class="evento-thumbnail" style="background-image: url('{{ evento.banner.url }}')"></div>
                                {% else %}
                                    <img src="{% static 'images/placeholder10.jpg' %}" alt="Banner do Evento" class="evento-thumbnail">
                                {% endif %}
                                <div class="evento-info">
                                    <h4>{{ evento.name }}</h4>
                                    <a href="{% url 'eventos:detalhes_evento' evento.id %}" class="btn btn-info">Detalhes</a>
                                    {% if perms.eventos.view_evento %}
                                        {% if request.user not in evento.clients.all %}
                                            <a href="{% url 'eventos:inscricao_evento' evento.id %}" class="btn btn-success">Inscrever-se</a>
                                        {% else %}
                                            <a href="#" onclick="confirmarCancelar('{{ evento.id }}')" class="btn btn-danger">Cancelar Inscrição</a>
                                        {% endif %}
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>

                <h5>Eventos Finalizados</h5>
                <div class="row" style="margin-bottom: 200px;">
                    {% for evento, certificados in eventos_e_certificados.items %}
                        <div class="col-md-4">
                            <div class="evento-card">
                                {% if evento.banner %}
                                    <div class="evento-thumbnail" style="background-image: url('{{ evento.banner.url }}')"></div>
                                {% else %}
                                    <img src="{% static 'images/placeholder10.jpg' %}" alt="Banner do Evento" class="evento-thumbnail">
                                {% endif %}
                                <div class="evento-info">
                                    <h4>{{ evento.name }}</h4>
                                    <a href="{% url 'eventos:detalhes_evento' evento.id %}" class="btn btn-info">Detalhes</a>
                                    {% if certificados %}
                                        <a href="{% url 'eventos:download_certificado' evento.id %}" class="btn btn-success" style="width: 150px;">
                                            <i class="bx bxs-download"></i> Certificado
                                        </a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

    <!-- Modal de Confirmação -->
    <div class="modal fade" id="confirmarModal" tabindex="-1" aria-labelledby="confirmarModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="confirmarModalLabel"></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    Tem certeza?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    <button type="button" class="btn btn-danger" id="confirmarBtn">Confirmar</button>
                </div>
            </div>
        </div>
    </div>

    <script src="{% static 'eventos/js/meuseventos.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script>
        var eventoIdParaCancelar;

        function confirmarCancelar(eventoId) {
            eventoIdParaCancelar = eventoId;
            $('#confirmarModalLabel').text('Cancelar Inscrição');
            $('#confirmarModal').modal('show');
            $('#confirmarBtn').off('click').on('click', function () {
                window.location.href = "{% url 'eventos:cancelar_inscricao' evento_id=0 %}".replace('0', eventoIdParaCancelar);
            });
        }
    </script>
{% endblock %}

eventos/templates/visualizarEvento.html
{% extends 'base.html' %}
{% load static %}

{% block 'head' %}
    <link rel="stylesheet" href="{% static 'eventos/css/visualizarEvento.css' %}">
{% endblock %}

{% block 'title' %}{{ evento.name }}{% endblock %}

{% block 'dashboard' %}
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                {% if evento.banner %}
                    <img src="{{ evento.banner.url }}" alt="Banner do Evento" class="img-fluid">
                {% else %}
                    <img src="{% static 'images/placeholder10.jpg' %}" alt="Banner do Evento" class="img-fluid">
                {% endif %}
            </div>
            <div class="col-md-6">
                <div class="row mt-4">
                    <div class="col-md-12">
                        <p>{{ evento.description }}</p>
                        <p><i class='bx bxs-calendar'></i> {{ evento.date }}</p>
                        <p><i class='bx bxs-time'></i> {{ evento.time }}</p>
                        <p><i class='bx bxs-map'></i> {{ evento.local }}</p>
                        <p><i class='bx bxs-category'></i> {{ evento.category }}</p>
                        <p><i class='bx bxs-user'></i> {{ evento.user }}</p>
                        {% if media_notas %}
                        <p><i class='bx bxs-star'></i> Avaliações: {{ media_notas|default:"Sem avaliações" }}</p>
                        {% endif %}
                        {% if evento.limite_inscricoes %}
                            {% if evento.limite_inscricoes == -1 %}
                                <p><i class='bx bxs-coupon'></i> Não possui limite de inscrições</p>
                            {% elif evento.clients.count >= evento.limite_inscricoes %}
                                <p><i class='bx bxs-coupon'></i> Esgotado</p>
                            {% else %}
                                <p><i class='bx bxs-coupon'></i> {{ evento.clients.count }} / {{ evento.limite_inscricoes }}</p>
                            {% endif %}
                        {% else %}
                            <p><i class='bx bxs-coupon'></i> Não possui limite de inscrições</p>
                        {% endif %}
                    </div>
                </div>
                {% if evento.finalizado %}
                    <div class="text-center mt-4">
                        <p>Evento finalizado</p>
                    </div>
                {% else %}
                    {% if perms.eventos.add_inscricao %}
                        {% if not request.user in evento.clients.all %}
                            {% if evento.limite_inscricoes is not None and evento.clients.count >= evento.limite_inscricoes %}
                                <div class="text-center mt-4">
                                    <p>Não há mais vagas disponíveis para este evento.</p>
                                </div>
                            {% else %}
                                <div class="text-center mt-4">
                                    <button class="btn btn-success" onclick="confirmarInscricao('{{ evento.id }}')">Inscrever-se</button>
                                </div>
                            {% endif %}
                        {% endif %}
                    {% endif %}
                {% endif %}
                {% if perms.eventos.change_evento and request.user == evento.user %}
                    <div class="text-center mt-4">
                        {% if not evento.finalizado %}
                        <a href="{% url 'eventos:editar_evento' evento.id %}" class="btn btn-warning">Editar</a>
                        <a href="#" onclick="confirmarFinalizar('{{ evento.id }}')" class="btn btn-success">Finalizar</a>
                        <a href="#" onclick="confirmarCancelar('{{ evento.id }}')" class="btn btn-danger">Cancelar</a>
                        {% endif %}
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
    {% if perms.eventos.add_evento %}
    {% if request.user == evento.user %}
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <p></p>
            <h4>Inscritos no Evento</h4>
            <ul>
                {% for cliente in evento.clients.all %}
                    <p>{{ cliente.username }} - {{ cliente.email }}</p>
                    
                {% empty %}
                    <p>Não há inscritos neste evento ainda.</p>
                {% endfor %}
            </ul>
            </div>
        </div>
    </div>
    {% endif %}
    {% endif %} 


    <div class="container">
        <div class="row" style="margin-bottom: 120px;">
            <div class="col-md-12">
                <p></p>
                <h4>Comentários</h4>
                <ul>
                    {% for avaliacao in comentarios %}
                        <li id="comentario-{{ avaliacao.id }}">
                            <div id="visualizar-comentario-{{ avaliacao.id }}">
                                <p><i class='bx bxs-user'></i> {{ avaliacao.user.username }}:   <i class='bx bxs-star'></i> {{ avaliacao.nota }}</p>
                                <p><i class='bx bx-comment-detail'></i> {{ avaliacao.comentario }}</p>
                                {% if request.user == avaliacao.user %}
                                <form action="{% url 'eventos:deletar_avaliacao' avaliacao.id %}" method="post" style="display: inline;">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-danger btn-sm" style="margin-bottom: 15px;">Deletar</button>
                                </form>
                            {% endif %}
                            </div>
                        </li>
                    {% empty %}
                        <p>Não há comentários neste evento ainda.</p>
                    {% endfor %}
                </ul>
                {% if request.user.is_authenticated %}
                {% if not request.user.avaliacao_set.exists %}
                {% if perms.eventos.add_inscricao and evento.finalizado %}
                        <h4>Deixe seu comentário</h4>
                    <form action="{% url 'eventos:enviar_avaliacao' evento.id %}" method="post">
                        {% csrf_token %}
                    <div class="form-group">
                            <label for="id_nota">Nota:</label>
                            <select name="nota" id="id_nota" class="form-control" required>
                                <option value="1">1 estrela</option>
                                <option value="2">2 estrelas</option>
                                <option value="3">3 estrelas</option>
                                <option value="4">4 estrelas</option>
                                <option value="5">5 estrelas</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="id_comentario">Comentário:</label>
                            <textarea class="form-control" id="id_comentario" name="comentario" rows="3" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-primary">Enviar Avaliação</button>
                    </form>
                    {% endif %}
                    {% endif %}
                    {% endif %}
            </div>
        </div>
    </div>

    <!-- Modal de Confirmação -->
    <div class="modal fade" id="confirmarModal" tabindex="-1" aria-labelledby="confirmarModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="confirmarModalLabel"></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    Tem certeza?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    <button type="button" class="btn btn-success" id="confirmarBtn">Confirmar</button>
                </div>
            </div>
        </div>
    </div>

    <script src="{% static 'eventos/js/meuseventos.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script>
        var eventoIdParaInscricao;
        var eventoIdParaCancelar;
        var eventoIdParaFinalizar;

        function confirmarInscricao(eventoId) {
            eventoIdParaInscricao = eventoId;
            $('#confirmarModalLabel').text('Inscrever-se no Evento');
            $('#confirmarModal').modal('show');
            $('#confirmarBtn').off('click').on('click', function () {
                window.location.href = "{% url 'eventos:inscricao_evento' evento_id=0 %}".replace('0', eventoIdParaInscricao);
            });
        }

        function confirmarCancelar(eventoId) {
            eventoIdParaCancelar = eventoId;
            $('#confirmarModalLabel').text('Cancelar Evento');
            $('#confirmarModal').modal('show');
            $('#confirmarBtn').off('click').on('click', function () {
                window.location.href = "{% url 'eventos:cancelar_evento' id=0 %}".replace('0', eventoIdParaCancelar);
            });
        }

        function confirmarFinalizar(eventoId) {
            eventoIdParaFinalizar = eventoId;
            $('#confirmarModalLabel').text('Finalizar Evento');
            $('#confirmarModal').modal('show');
            $('#confirmarBtn').off('click').on('click', function () {
                window.location.href = "{% url 'eventos:finalizar_evento' id=0 %}".replace('0', eventoIdParaFinalizar);
            });
        }
    </script>
{% endblock %}